name: Deploy dev

on:
  push:
    branches:
    - dev2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Install dependencies
      run: yarn install

    env:
        CI: false

    - name: Build React App
      run: yarn build

    - uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.BOT_GA_STATICWEBSITES_ENG_AWS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.BOT_GA_STATICWEBSITES_ENG_AWS_SECRET }} 
        AWS_REGION: 'ap-southeast-1'   # optional: defaults to us-east-1
        AWS_S3_BUCKET: piktekk-homepage
        SOURCE_DIR: 'build'      # optional: defaults to entire repository

        # Invalidate Cache in CFD
    - name: invalidate
      uses: chetan/invalidate-cloudfront-action@65a60c4d1af7dfe59c92acaaa390ba25f8f29a87
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.BOT_GA_STATICWEBSITES_ENG_AWS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.BOT_GA_STATICWEBSITES_ENG_AWS_SECRET }} 
        AWS_REGION: 'ap-southeast-1'
        DISTRIBUTION: E3FS567HUBR5HG
        PATHS: '/*'
